/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/Auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LoginGoogleCommand"];
                    "text/json": components["schemas"]["LoginGoogleCommand"];
                    "application/*+json": components["schemas"]["LoginGoogleCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LoginResponse"];
                        "application/json": components["schemas"]["LoginResponse"];
                        "text/json": components["schemas"]["LoginResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Auth/google/iniciar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    returnUrl?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    code?: string;
                    state?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Autores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AutorResponsePagina"];
                        "application/json": components["schemas"]["AutorResponsePagina"];
                        "text/json": components["schemas"]["AutorResponsePagina"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/posts/{postId}/comentarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    Page?: number;
                    PageSize?: number;
                    OrderBy?: string;
                    Filter?: string;
                };
                header?: never;
                path: {
                    postId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ComentarioListaResponsePagina"];
                        "application/json": components["schemas"]["ComentarioListaResponsePagina"];
                        "text/json": components["schemas"]["ComentarioListaResponsePagina"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    postId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CriarComentarioRequest"];
                    "text/json": components["schemas"]["CriarComentarioRequest"];
                    "application/*+json": components["schemas"]["CriarComentarioRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ComentarioResponse"];
                        "application/json": components["schemas"]["ComentarioResponse"];
                        "text/json": components["schemas"]["ComentarioResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/posts/{postId}/comentarios/{id}/ocultar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    postId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/v1/posts/{postId}/comentarios/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    postId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/posts/{postId}/curtidas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    postId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    postId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Etapas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["EtapaResponse"][];
                        "application/json": components["schemas"]["EtapaResponse"][];
                        "text/json": components["schemas"]["EtapaResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Imagens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        arquivo?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ImagemResponse"];
                        "application/json": components["schemas"]["ImagemResponse"];
                        "text/json": components["schemas"]["ImagemResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Links/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    url?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LinkPreviewResponse"];
                        "application/json": components["schemas"]["LinkPreviewResponse"];
                        "text/json": components["schemas"]["LinkPreviewResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    IncluirRascunhos?: boolean;
                    Page?: number;
                    PageSize?: number;
                    OrderBy?: string;
                    Filter?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PostResumoResponsePagina"];
                        "application/json": components["schemas"]["PostResumoResponsePagina"];
                        "text/json": components["schemas"]["PostResumoResponsePagina"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CriarPostRequest"];
                    "text/json": components["schemas"]["CriarPostRequest"];
                    "application/*+json": components["schemas"]["CriarPostRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PostResponse"];
                        "application/json": components["schemas"]["PostResponse"];
                        "text/json": components["schemas"]["PostResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Posts/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PostDetalheResponse"];
                        "application/json": components["schemas"]["PostDetalheResponse"];
                        "text/json": components["schemas"]["PostDetalheResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Posts/id/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PostDetalheResponse"];
                        "application/json": components["schemas"]["PostDetalheResponse"];
                        "text/json": components["schemas"]["PostDetalheResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Posts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["EditarPostRequest"];
                    "text/json": components["schemas"]["EditarPostRequest"];
                    "application/*+json": components["schemas"]["EditarPostRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PostResponse"];
                        "application/json": components["schemas"]["PostResponse"];
                        "text/json": components["schemas"]["PostResponse"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    Page?: number;
                    PageSize?: number;
                    OrderBy?: string;
                    Filter?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TagResponsePagina"];
                        "application/json": components["schemas"]["TagResponsePagina"];
                        "text/json": components["schemas"]["TagResponsePagina"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CriarTagCommand"];
                    "text/json": components["schemas"]["CriarTagCommand"];
                    "application/*+json": components["schemas"]["CriarTagCommand"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TagResponse"];
                        "application/json": components["schemas"]["TagResponse"];
                        "text/json": components["schemas"]["TagResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Tags/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Usuarios/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PerfilResponse"];
                        "application/json": components["schemas"]["PerfilResponse"];
                        "text/json": components["schemas"]["PerfilResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AutorResponse: {
            /** Format: uuid */
            id?: string;
            nome?: string | null;
            imagemUrl?: string | null;
            bio?: string | null;
        };
        AutorResponsePagina: {
            items?: components["schemas"]["AutorResponse"][] | null;
            /** Format: int32 */
            totalItems?: number;
        };
        Bloco: {
            id?: string | null;
            tipo?: components["schemas"]["TipoBloco"];
            /** Format: int32 */
            ordem?: number;
            html?: string | null;
            imagemPath?: string | null;
            imagemUrl?: string | null;
            alt?: string | null;
            /** Format: double */
            aspectRatio?: number | null;
            linkUrl?: string | null;
            linkTitulo?: string | null;
            linkDescricao?: string | null;
            linkThumbnail?: string | null;
            linkSiteName?: string | null;
        };
        ComentarioListaResponse: {
            /** Format: uuid */
            id?: string;
            autor?: string | null;
            conteudo?: string | null;
            /** Format: date-time */
            dataCriacao?: string;
            respostas?: components["schemas"]["RespostaResponse"][] | null;
        };
        ComentarioListaResponsePagina: {
            items?: components["schemas"]["ComentarioListaResponse"][] | null;
            /** Format: int32 */
            totalItems?: number;
        };
        ComentarioResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            postId?: string;
            /** Format: uuid */
            parentId?: string | null;
            autor?: string | null;
            conteudo?: string | null;
            aprovado?: boolean;
        };
        CriarComentarioRequest: {
            /** Format: uuid */
            parentId?: string | null;
            autor?: string | null;
            conteudo?: string | null;
        };
        CriarPostRequest: {
            titulo?: string | null;
            imagemCapa?: string | null;
            tagIds?: string[] | null;
            conteudo?: components["schemas"]["Bloco"][] | null;
            status?: components["schemas"]["StatusPost"];
            dek?: string | null;
            moods?: components["schemas"]["Mood"][] | null;
            /** Format: uuid */
            etapaId?: string | null;
            /** Format: date-time */
            dataPublicacao?: string | null;
        };
        CriarTagCommand: {
            nome?: string | null;
        };
        EditarPostRequest: {
            titulo?: string | null;
            imagemCapa?: string | null;
            tagIds?: string[] | null;
            conteudo?: components["schemas"]["Bloco"][] | null;
            status?: components["schemas"]["StatusPost"];
            dek?: string | null;
            moods?: components["schemas"]["Mood"][] | null;
            /** Format: uuid */
            etapaId?: string | null;
            /** Format: date-time */
            dataPublicacao?: string | null;
        };
        EtapaResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: int32 */
            numero?: number;
            titulo?: string | null;
            descricao?: string | null;
            refs?: string | null;
        };
        ImagemResponse: {
            path?: string | null;
            url?: string | null;
        };
        LinkPreviewResponse: {
            url?: string | null;
            titulo?: string | null;
            descricao?: string | null;
            thumbnail?: string | null;
            siteName?: string | null;
        };
        LoginGoogleCommand: {
            idToken?: string | null;
        };
        LoginResponse: {
            token?: string | null;
            nome?: string | null;
            imagemUrl?: string | null;
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        Mood: 0 | 1 | 2 | 3 | 4;
        PerfilResponse: {
            /** Format: uuid */
            id?: string;
            nome?: string | null;
            email?: string | null;
            imagemUrl?: string | null;
            isAdmin?: boolean;
        };
        PostDetalheResponse: {
            /** Format: uuid */
            id?: string;
            titulo?: string | null;
            dek?: string | null;
            slug?: string | null;
            imagemCapa?: string | null;
            conteudo?: components["schemas"]["Bloco"][] | null;
            /** Format: int32 */
            tempoLeitura?: number;
            /** Format: int32 */
            qtdCurtidas?: number;
            /** Format: int32 */
            qtdVisualizacoes?: number;
            /** Format: date-time */
            dataCriacao?: string;
            /** Format: date-time */
            dataAtualizacao?: string;
            autor?: components["schemas"]["AutorResponse"];
            tags?: components["schemas"]["TagResponse"][] | null;
            /** Format: date-time */
            dataPublicacao?: string | null;
            moods?: components["schemas"]["Mood"][] | null;
            etapa?: components["schemas"]["EtapaResponse"];
        };
        PostResponse: {
            /** Format: uuid */
            id?: string;
            titulo?: string | null;
            slug?: string | null;
            /** Format: int32 */
            tempoLeitura?: number;
        };
        PostResumoResponse: {
            /** Format: uuid */
            id?: string;
            titulo?: string | null;
            dek?: string | null;
            slug?: string | null;
            imagemCapa?: string | null;
            /** Format: int32 */
            tempoLeitura?: number;
            /** Format: int32 */
            qtdCurtidas?: number;
            /** Format: int32 */
            qtdVisualizacoes?: number;
            /** Format: date-time */
            dataCriacao?: string;
            autor?: components["schemas"]["AutorResponse"];
            tags?: components["schemas"]["TagResponse"][] | null;
            status?: components["schemas"]["StatusPost"];
            /** Format: date-time */
            dataPublicacao?: string | null;
            moods?: components["schemas"]["Mood"][] | null;
            etapa?: components["schemas"]["EtapaResponse"];
        };
        PostResumoResponsePagina: {
            items?: components["schemas"]["PostResumoResponse"][] | null;
            /** Format: int32 */
            totalItems?: number;
        };
        RespostaResponse: {
            /** Format: uuid */
            id?: string;
            autor?: string | null;
            conteudo?: string | null;
            /** Format: date-time */
            dataCriacao?: string;
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        StatusPost: 0 | 1 | 2;
        TagResponse: {
            /** Format: uuid */
            id?: string;
            nome?: string | null;
            slug?: string | null;
        };
        TagResponsePagina: {
            items?: components["schemas"]["TagResponse"][] | null;
            /** Format: int32 */
            totalItems?: number;
        };
        /**
         * Format: int32
         * @enum {integer}
         */
        TipoBloco: 0 | 1 | 2;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
